options(tinytex.verbose = TRUE)
setwd("~/GitHub/cv")
name <- "stevenmyles"
cv <- paste0(name, "_cv")
pdf_Rmd <- paste0("_", cv, ".Rmd")
pdf_out <- paste0(cv, ".pdf")
require(rmarkdown)
require(tinytex)
render_site()
render(pdf_Rmd, output_format = "pdf_document", output_file = pdf_out)
invisible(file.remove("index.pdf"))
